export const topicOptions = [
  "Array",
  "String",
  "Hash Table",
  "Dynamic Programming",
  "Math",
  "Sorting",
  "Greedy",
  "Depth-First-Search",
  "Binary Search",
  "Database",
  "Breadth-First Search",
  "Tree",
  "Matrix",
  "Two Pointers Bit Manipulation",
  "Binary Tree",
  "Heap (Priority Queue)",
  "Stack",
  "Prefix Sum",
  "Simulation",
  "Graph",
  "Desgin",
  "Counting",
  "Sliding Window",
  "Backtracking",
  "Union Find",
  "Enumeration",
  "Linked List",
  "Ordered Set",
  "Monotonic Stack",
  "Number Theory",
  "Trie",
  "Divide and Conquer",
  "Recursion",
  "Bitmask",
  "Queue",
  "Binaray Search Tree",
  "Segment Tree",
  "Memoriztion",
  "Geometry",
];
